spring.application.name=SistemaDeSenhas
spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/sistemadesenhas_db
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true